using System.Text;

namespace Youtube_Downloader;

/// <summary>
/// Manages YouTube cookie storage and file generation for yt-dlp.
/// Handles decryption of stored cookies and conversion to Netscape format.
/// </summary>
public static class YouTubeCookieManager
{
    private static readonly string CookieFilePath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "YoutubeDownloader",
        "youtube_cookies.txt");

    /// <summary>
    /// Gets the path to the cookie file if YouTube login is active.
    /// Writes the decrypted cookies to a file in Netscape format.
    /// </summary>
    /// <param name="config">The application config</param>
    /// <returns>Path to the cookie file, or null if not logged in</returns>
    public static string? GetCookiesFilePath(Config config)
    {
        if (!config.YouTubeLoggedIn || string.IsNullOrEmpty(config.YouTubeCookiesEncrypted))
            return null;

        try
        {
            // Decrypt the stored cookies
            string cookieData = CookieEncryption.Decrypt(config.YouTubeCookiesEncrypted);
            if (string.IsNullOrEmpty(cookieData))
                return null;

            // Ensure directory exists
            string? dir = Path.GetDirectoryName(CookieFilePath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            // Write to file (use UTF8 without BOM - yt-dlp requires this)
            File.WriteAllText(CookieFilePath, cookieData, new UTF8Encoding(false));
            return CookieFilePath;
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// Deletes the cookie file if it exists.
    /// </summary>
    public static void DeleteCookieFile()
    {
        try
        {
            if (File.Exists(CookieFilePath))
            {
                File.Delete(CookieFilePath);
            }
        }
        catch
        {
            // Ignore deletion errors
        }
    }

    /// <summary>
    /// Converts WebView2 cookies to Netscape cookie format.
    /// </summary>
    /// <param name="cookies">List of cookies from WebView2</param>
    /// <returns>Cookie data in Netscape format</returns>
    public static string ConvertToNetscapeFormat(List<CookieData> cookies)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Netscape HTTP Cookie File");
        sb.AppendLine("# https://curl.haxx.se/docs/http-cookies.html");
        sb.AppendLine("# This file was generated by YouTube Downloader");
        sb.AppendLine();

        foreach (var cookie in cookies)
        {
            // Netscape format: domain, tailmatch, path, secure, expiry, name, value
            string domain = cookie.Domain;
            string tailmatch = domain.StartsWith(".") ? "TRUE" : "FALSE";
            string path = cookie.Path;
            string secure = cookie.IsSecure ? "TRUE" : "FALSE";
            string expiry = cookie.Expires > 0 ? cookie.Expires.ToString() : "0";
            string name = cookie.Name;
            string value = cookie.Value;

            sb.AppendLine($"{domain}\t{tailmatch}\t{path}\t{secure}\t{expiry}\t{name}\t{value}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Saves cookies to the config (encrypted).
    /// </summary>
    /// <param name="config">The application config</param>
    /// <param name="cookieData">Cookie data in Netscape format</param>
    /// <param name="email">Optional email address for display</param>
    public static void SaveCookies(Config config, string cookieData, string? email = null)
    {
        config.YouTubeCookiesEncrypted = CookieEncryption.Encrypt(cookieData);
        config.YouTubeLoggedIn = true;
        config.YouTubeLoginEmail = email ?? "";
        config.Save();
    }

    /// <summary>
    /// Clears stored cookies (sign out).
    /// </summary>
    /// <param name="config">The application config</param>
    public static void ClearCookies(Config config)
    {
        config.YouTubeCookiesEncrypted = "";
        config.YouTubeLoggedIn = false;
        config.YouTubeLoginEmail = "";
        config.Save();
        DeleteCookieFile();
    }
}

/// <summary>
/// Simple cookie data structure for conversion.
/// </summary>
public class CookieData
{
    public string Domain { get; set; } = "";
    public string Path { get; set; } = "/";
    public string Name { get; set; } = "";
    public string Value { get; set; } = "";
    public bool IsSecure { get; set; }
    public long Expires { get; set; }
}
